# Generated by Django 4.0.3 on 2022-04-13 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='imge',
        ),
        migrations.AddField(
            model_name='team',
            name='imga',
            field=models.ImageField(default='arathi', upload_to='pics'),
            preserve_default=False,
        ),
    ]
